baseURL = 'https://anirudha.co'
languageCode = 'en-us'
title = 'Anirudha Bose'
theme = 'cactus'
copyright = "Anirudha Bose"

#[[menu.main]]
#  name = "Home"
#  url = "/"
#  weight = 1
#
#[[menu.main]]
#  name = "Writings"
#  url = "/posts"
#  weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

  [markup.goldmark.renderer]
    unsafe= true

[params]
  mainSection = "posts"
  mainSectionTitle = "Blog"
  tagsOverview = false
  tocInline = false
  showAllPostsOnHomePage = false
  showProjectsList = false

  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/onybose"
  [[params.social]]
    name = "github"
    link = "https://github.com/onyb"
  [[params.social]]
    name = "linkedin"
    link = "https://linkedin.com/in/onyb"
