name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'

    - name: Setup Git
      uses: ludeeus/action-push@0.0.1
      env:
        ACTION_MAIL: 'anirudha.bose@alumni.cern'
        ACTION_NAME: 'Anirudha Bose'
        ACTION_BRANCH: 'master'
        ACTION_MESSAGE: 'GitHub Actions push'

    - name: Install dependencies
      run: yarn

    - name: Deploy
      run: yarn deploy
