name: CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.1'

    - name: Setup Git
      run: |
        git config --global user.email "anirudha.bose@alumni.cern"
        git config --global user.name "Anirudha Bose"

    - name: Install dependencies
      run: yarn

    - name: Deploy
      run: yarn deploy
      env:
        GH_TOKEN: '6b35dbddd823ff3e3f752f66beda592f25e7bdf2'
